DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  dob DATE NOT NULL,
  email VARCHAR(255) NOT NULL,
  post_code VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  user_pic VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS types CASCADE;

CREATE TABLE types (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);

DROP TABLE IF EXISTS time_period CASCADE;

CREATE TABLE time_period (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);

DROP TABLE IF EXISTS listings CASCADE;
CREATE TABLE listings (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  date_posted DATE DEFAULT CURRENT_DATE,
  price INTEGER NOT NULL,
  description TEXT,
  picture VARCHAR(255) NOT NULL,
  type_id INTEGER REFERENCES types(id) NOT NULL,
  visits INTEGER DEFAULT 0,
  time_period_id INTEGER REFERENCES time_period(id) NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  sold BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS user_favorite CASCADE;

CREATE TABLE user_favorite (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  listing_id INTEGER REFERENCES listings(id) NOT NULL
);

DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,
  user_sender_id INTEGER REFERENCES users(id) NOT NULL,
  listing_id INTEGER REFERENCES listings(id) NOT NULL,
  message TEXT
);
